import React from 'react';
import MoneyPageTemplate, { MoneyPageData } from '../../components/MoneyPageTemplate';

const data: MoneyPageData = {
  slug: 'rhinoplasty-hyderabad',
  procedureName: 'Rhinoplasty',
  seoTitle: 'Rhinoplasty Hyderabad ★ from ₹70K | Dr. Ram Prabhu DNB',
  seoDescription:
    'Open & closed rhinoplasty in Kondapur Hyderabad — nose reshaping, hump reduction, tip refinement, deviated septum correction. Dr. Ram Prabhu, DNB Plastic Surgery, 16+ years. Call 9949808628.',
  seoKeywords: [
    'rhinoplasty hyderabad',
    'rhinoplasty in hyderabad',
    'best rhinoplasty surgeon in hyderabad',
    'nose surgery hyderabad',
    'nose job hyderabad',
    'rhinoplasty cost hyderabad',
    'septoplasty rhinoplasty hyderabad',
    'revision rhinoplasty india',
    'tip rhinoplasty hyderabad',
  ],
  h1: 'Rhinoplasty in Hyderabad — Natural Nose Reshaping by Dr. Ram Prabhu',
  heroSubheadline:
    'Open and closed rhinoplasty performed by a DNB Super Speciality Plastic Surgeon. Hump reduction, tip refinement, septum correction, and ethnic-appropriate reshaping. Day-care surgery with subtle, natural results.',
  heroBadges: [
    '★ DNB Plastic Surgery',
    '500+ Nose Cases',
    'Open & Closed Technique',
    'Functional + Aesthetic',
    '0% EMI',
  ],
  heroPriceBand: 'Rhinoplasty from ₹70,000',
  heroImage: 'https://drramprabhu.com/images/breast/Gynecomastia.jpg',
  priceMin: '70000',
  priceMax: '180000',
  whatIsParagraphs: [
    'Rhinoplasty — commonly called a "nose job" — is a surgical procedure that reshapes the nose to improve appearance, breathing, or both. It can address a dorsal hump, drooping or bulbous tip, wide nostrils, deviated septum, asymmetry from injury, or congenital deformity. As the central feature of the face, even a 1-2 mm change can dramatically alter facial harmony.',
    'At our Kondapur clinic, Dr. Ram Prabhu performs both open and closed rhinoplasty using techniques tailored to Indian and South Asian noses, where preserving ethnic character while making subtle refinements is the priority. Functional rhinoplasty (correcting breathing problems from a deviated septum or collapsed valves) is often combined with aesthetic refinement in a single procedure.',
    'Rhinoplasty is one of the most technically demanding plastic surgery procedures because the nose is a 3D structure of cartilage, bone, and skin — every adjustment must balance form, function, and long-term healing. Dr. Ram Prabhu has performed 500+ rhinoplasty procedures across primary and revision cases.',
  ],
  causes: [
    'Dorsal hump (bony or cartilaginous bump on the bridge)',
    'Drooping, bulbous, or under-projected nasal tip',
    'Wide, flared, or asymmetric nostrils',
    'Deviated septum causing breathing difficulty',
    'Saddle nose deformity (from trauma or congenital)',
    'Crooked nose after injury or fracture',
    'Disproportion between nose and other facial features',
    'Previous unsatisfactory rhinoplasty (revision)',
    'Cleft lip-related nasal deformity',
    'Functional issues — chronic nasal obstruction, snoring',
  ],
  symptoms: [
    'Self-consciousness about the side or front profile',
    'Difficulty breathing through one or both nostrils',
    'Photographs you avoid because of your nose',
    'Asymmetry following an old fracture',
    'Bridge bump that catches glasses',
    'Tip that droops further when smiling',
    'Persistent sinus issues with structural cause',
  ],
  procedures: [
    {
      title: 'Closed Rhinoplasty',
      description: 'All incisions hidden inside the nostrils — no external scars. Best for limited dorsal/tip refinements.',
      bestFor: 'Mild hump, small tip refinement',
      duration: '1.5-2 hrs',
      anesthesia: 'General',
      stay: 'Day-care',
      price: '₹70,000 — ₹1,00,000',
    },
    {
      title: 'Open Rhinoplasty',
      description: 'Small incision across the columella for direct visualization of nasal structure. Gold standard for complex reshaping.',
      bestFor: 'Tip projection, twisted nose, revision',
      duration: '2-3 hrs',
      anesthesia: 'General',
      stay: 'Day-care',
      price: '₹90,000 — ₹1,30,000',
    },
    {
      title: 'Septorhinoplasty (Functional + Cosmetic)',
      description: 'Combines septum straightening (for breathing) with cosmetic reshaping in a single procedure.',
      bestFor: 'Deviated septum + aesthetic concerns',
      duration: '2.5-3.5 hrs',
      anesthesia: 'General',
      stay: 'Day-care or 1 day',
      price: '₹1,00,000 — ₹1,40,000',
    },
    {
      title: 'Revision Rhinoplasty',
      description: 'Correction of unsatisfactory results from a previous rhinoplasty. Often requires cartilage grafting from ear or rib.',
      bestFor: 'Previous unsatisfactory surgery',
      duration: '3-4 hrs',
      anesthesia: 'General',
      stay: '1 day',
      price: '₹1,20,000 — ₹1,80,000',
    },
    {
      title: 'Tip Rhinoplasty',
      description: 'Refines only the nasal tip without altering the bridge. Suitable for bulbous, drooping, or under-projected tips.',
      bestFor: 'Tip-only concerns',
      duration: '1-1.5 hrs',
      anesthesia: 'Local + sedation',
      stay: 'Day-care',
      price: '₹70,000 — ₹95,000',
    },
    {
      title: 'Ethnic Rhinoplasty (South Asian)',
      description: 'Tailored to Indian/South Asian noses — preserves ethnic identity while refining specific features. Often uses cartilage grafts.',
      bestFor: 'Indian / South Asian features',
      duration: '2.5-3 hrs',
      anesthesia: 'General',
      stay: 'Day-care',
      price: '₹95,000 — ₹1,40,000',
    },
  ],
  walkthrough: [
    { step: 'Step 1', title: 'Arrival & Pre-op (45 min)', detail: 'Final consent, vitals, pre-op photographs from 5 angles. Markings made while you are upright.' },
    { step: 'Step 2', title: 'Anaesthesia (15 min)', detail: 'General anaesthesia for most rhinoplasty cases (light tip rhinoplasty may be done under local + sedation).' },
    { step: 'Step 3', title: 'Incisions (10 min)', detail: 'For closed approach — entirely inside the nostrils. For open — a small inverted-V across the columella, designed to heal invisibly.' },
    { step: 'Step 4', title: 'Reshaping (60-120 min)', detail: 'Hump reduction with rasps and osteotomes; tip refinement with suture techniques; cartilage grafts from septum or ear if needed.' },
    { step: 'Step 5', title: 'Closure (15 min)', detail: 'Skin closed with fine absorbable sutures. Internal silastic splints support the septum if corrected.' },
    { step: 'Step 6', title: 'Splint & Dressing (10 min)', detail: 'External plaster or thermoplastic splint applied for 5-7 days. Light gauze dressing under the nostrils.' },
    { step: 'Step 7', title: 'Recovery & Discharge (2-3 hrs)', detail: 'Observation for 2-3 hours. Most patients go home the same day with detailed care instructions.' },
  ],
  recovery: [
    { when: 'Day 0', title: 'Surgery day', detail: 'Light bruising under the eyes. External splint protects the nose. Mild headache and stuffiness are normal.' },
    { when: 'Day 1-3', title: 'Peak swelling', detail: 'Bruising peaks. Sleep elevated. Cold compresses help. Pain managed with oral medication.' },
    { when: 'Day 5-7', title: 'Splint removal', detail: 'External splint comes off. First glimpse of new shape (still swollen). Bruises rapidly fading.' },
    { when: 'Week 2-3', title: 'Return to work', detail: 'Most desk-job patients return to work after 1 week. Avoid contact sports, glasses, and heavy lifting.' },
    { when: 'Week 4-6', title: 'Light activity', detail: 'Gym (cardio) okay. Glasses can rest gently on the bridge. 60-70% of swelling has resolved.' },
    { when: 'Month 3', title: '80% final shape', detail: 'Most swelling resolved. Tip is still slightly firm. Photographs look very close to final.' },
    { when: 'Month 12', title: 'Final result', detail: 'Complete settling of all swelling. Final tip definition visible. Permanent results.' },
  ],
  beforeAfterImage: '/images/breast/Gynecomastia-before-after.jpeg',
  faqs: [
    {
      q: 'How long does rhinoplasty surgery take?',
      a: 'Primary rhinoplasty typically takes 1.5 to 3 hours depending on technique (closed vs open) and complexity. Revision cases or septorhinoplasty may take 3-4 hours. Most cases are day-care; some septorhinoplasty cases stay one night.',
    },
    {
      q: 'What is the cost of rhinoplasty in Hyderabad?',
      a: 'Rhinoplasty cost ranges from ₹70,000 to ₹1,80,000. Closed rhinoplasty: ₹70K-₹1L. Open rhinoplasty: ₹90K-₹1.3L. Septorhinoplasty: ₹1L-₹1.4L. Revision: ₹1.2L-₹1.8L. Cost depends on complexity, cartilage graft requirement, anaesthesia type, and hospital stay.',
    },
    {
      q: 'Will there be visible scars after rhinoplasty?',
      a: 'Closed rhinoplasty leaves no external scars (all incisions inside the nostrils). Open rhinoplasty has a tiny inverted-V incision across the columella that fades to invisibility within 6 months. Revision cases may use the same path as the original incision.',
    },
    {
      q: 'How painful is rhinoplasty recovery?',
      a: 'Surprisingly, rhinoplasty is not very painful — most patients describe pressure and stuffiness rather than pain. Bruising and swelling cause more discomfort than pain itself. Pain medication is needed for 2-3 days, then over-the-counter analgesics suffice.',
    },
    {
      q: 'How long until I see the final result of rhinoplasty?',
      a: 'You will see a "rough" result at 1 week (after splint removal), but tip swelling takes 6-12 months to fully resolve. The bridge settles by 2-3 months. Final, refined definition — especially of the tip — is visible at 12 months.',
    },
    {
      q: 'Can I get rhinoplasty without breaking my nose?',
      a: 'If your concern is the tip, nostrils, or non-bony parts, the bone may not need to be touched. However, dorsal hump removal or correcting deviation almost always requires controlled osteotomies (bone cuts) to reshape the bridge. These are precise and predictable.',
    },
    {
      q: 'Is rhinoplasty safe? What are the risks?',
      a: 'Rhinoplasty is generally very safe in experienced hands. Risks include bleeding, infection (rare), scar issues, nasal obstruction, asymmetry, and rarely — need for revision. Dr. Ram Prabhu uses advanced techniques and follows strict safety protocols. Pre-op evaluation rules out anatomical or medical risk factors.',
    },
    {
      q: 'Can rhinoplasty improve my breathing?',
      a: 'Yes — septorhinoplasty corrects deviated septum, collapsed nasal valves, and turbinate hypertrophy that impair breathing. Many patients undergoing cosmetic rhinoplasty also notice breathing improvement because functional issues are addressed simultaneously.',
    },
    {
      q: 'When can I wear glasses after rhinoplasty?',
      a: 'Avoid glasses resting on the nasal bridge for 4-6 weeks. Use contact lenses, tape glasses to the forehead, or use a "nose splint pad" cushion. After 6 weeks, gentle bridge resting is fine.',
    },
    {
      q: 'Will rhinoplasty look obvious or "done"?',
      a: 'Modern rhinoplasty aims for natural, balanced results — not a "done" look. Dr. Ram Prabhu emphasizes preserving ethnic features and facial harmony. Most patients\' friends notice they look better but cannot identify what changed.',
    },
    {
      q: 'Can I combine rhinoplasty with chin augmentation or other procedures?',
      a: 'Yes — rhinoplasty is commonly combined with chin augmentation (genioplasty) since chin projection significantly affects how the nose appears. Combining procedures saves on anaesthesia and recovery time.',
    },
    {
      q: 'How do I book a rhinoplasty consultation?',
      a: 'Call or WhatsApp 9949808628 to schedule a consultation. The clinic is at Idea Clinic, Kondapur, Hyderabad — Mon-Sat, 10AM-12PM and 7PM-8PM. Online consultations with photo review are available for outstation patients.',
    },
  ],
  formGradeOptions: [
    'Hump reduction (bridge)',
    'Tip refinement',
    'Width / nostril reduction',
    'Deviated septum correction',
    'Revision rhinoplasty',
    'Not sure — need consultation',
  ],
  formSubject: 'New Rhinoplasty Consultation Request',
  whatsappMessage: 'Hello Dr. Ram Prabhu, I would like to book a rhinoplasty consultation. Please share available slots and pricing.',
  relatedPages: [
    { url: '/gynecomastia', label: 'Gynecomastia Surgery' },
    { url: '/services/facelift', label: 'Facelift' },
    { url: '/services/body-contouring', label: 'Body Contouring' },
  ],
};

const RhinoplastyHyderabad: React.FC = () => <MoneyPageTemplate data={data} />;
export default RhinoplastyHyderabad;
