import React from 'react';
import MoneyPageTemplate, { MoneyPageData } from '../../components/MoneyPageTemplate';

const data: MoneyPageData = {
  slug: 'tummy-tuck-hyderabad',
  procedureName: 'Tummy Tuck (Abdominoplasty)',
  seoTitle: 'Tummy Tuck Hyderabad ★ Mommy Makeover | Dr. Ram Prabhu DNB',
  seoDescription:
    'Tummy tuck (abdominoplasty) in Kondapur Hyderabad — full, mini, post-pregnancy mommy makeover. Dr. Ram Prabhu, DNB Plastic Surgery, 16+ years. From ₹1.4L. 0% EMI. Call 9949808628.',
  seoKeywords: [
    'tummy tuck hyderabad',
    'tummy tuck surgery cost near me',
    'abdominoplasty near me',
    'post pregnancy tummy tuck',
    'mommy makeover hyderabad',
    'mommy makeover india',
    'mini tummy tuck hyderabad',
    'can i have a baby after tummy tuck',
    'tummy tuck specialist near me',
  ],
  h1: 'Tummy Tuck in Hyderabad — Post-Pregnancy & Post-Weight-Loss Abdominoplasty',
  heroSubheadline:
    'Full, mini, and extended tummy tuck performed by Dr. Ram Prabhu, DNB Super Speciality Plastic Surgeon. Restores flat, firm abdomen after pregnancy or major weight loss. Often combined with liposuction.',
  heroBadges: [
    '★ DNB Plastic Surgery',
    'Full / Mini / Extended',
    'Mommy Makeover',
    'Muscle Repair',
    '0% EMI',
  ],
  heroPriceBand: 'Tummy Tuck from ₹1,40,000',
  heroImage: 'https://drramprabhu.com/images/body/tummy.webp',
  priceMin: '140000',
  priceMax: '280000',
  whatIsParagraphs: [
    'A tummy tuck (abdominoplasty) addresses three problems liposuction cannot fix: loose abdominal skin, separated abdominal muscles (diastasis recti), and stretch marks below the navel. It is the gold-standard procedure for women who have completed pregnancy or anyone who has experienced significant weight loss and is left with hanging skin.',
    'Unlike liposuction, which only removes fat through small incisions, a tummy tuck involves an incision low across the bikini line — designed to be hidden by underwear. Through this access, Dr. Ram Prabhu repairs separated muscles (creating an "internal corset"), removes excess skin, repositions the navel, and tightens the abdominal contour.',
    'At our Kondapur clinic, we tailor the procedure: mini tummy tuck for limited lower-abdomen looseness, full tummy tuck for typical post-pregnancy presentation, and extended (with hip/back skin) for post-bariatric patients. Most procedures combine liposuction of the flanks for a circumferential result — known as a 360° body contouring.',
    'Tummy tuck is also the cornerstone of a "mommy makeover" — typically combining tummy tuck with breast lift/augmentation to restore pre-pregnancy body contour.',
  ],
  causes: [
    'Pregnancy stretching of skin and abdominal muscles',
    'Diastasis recti (separation of abdominal muscles)',
    'Significant weight loss (50+ kg) leaving hanging skin',
    'Post-bariatric surgery body contouring needs',
    'Multiple pregnancies / twin / triplet pregnancies',
    'Genetic skin laxity that does not retract with exercise',
    'C-section scar deformity ("apron" overhang)',
    'Stretch marks that no cream can resolve (only excision works)',
  ],
  symptoms: [
    'Loose abdominal skin that does not respond to exercise',
    'Visible muscle separation when contracting abdomen',
    'Skin overhang below the navel ("apron")',
    'Stretch marks across the lower abdomen',
    'Difficulty fitting into pre-pregnancy clothes',
    'Lower back pain from weak core muscles',
    'Skin irritation under abdominal skin fold',
    'Self-consciousness in fitted clothing or swimwear',
  ],
  procedures: [
    {
      title: 'Mini Tummy Tuck',
      description: 'Shorter incision, addresses lower abdomen only. No navel repositioning.',
      bestFor: 'Limited lower-abdomen looseness',
      duration: '2-3 hrs',
      anesthesia: 'General',
      stay: 'Day-care',
      price: '₹1,40,000 — ₹1,80,000',
    },
    {
      title: 'Full Tummy Tuck',
      description: 'Standard procedure — full abdominal skin removal, muscle repair, navel repositioning.',
      bestFor: 'Post-pregnancy, moderate skin excess',
      duration: '3-4 hrs',
      anesthesia: 'General',
      stay: '1-2 days',
      price: '₹1,80,000 — ₹2,20,000',
    },
    {
      title: 'Extended Tummy Tuck',
      description: 'Extends incision to hips/back. For significant weight loss patients with circumferential excess.',
      bestFor: 'Post-bariatric, hip rolls',
      duration: '4-5 hrs',
      anesthesia: 'General',
      stay: '2 days',
      price: '₹2,20,000 — ₹2,80,000',
    },
    {
      title: 'Tummy Tuck + Liposuction (360°)',
      description: 'Combines abdominoplasty with circumferential lipo of flanks/back for complete contouring.',
      bestFor: 'Comprehensive midsection sculpting',
      duration: '4-5 hrs',
      anesthesia: 'General',
      stay: '1-2 days',
      price: '₹2,20,000 — ₹2,80,000',
    },
    {
      title: 'Mommy Makeover',
      description: 'Tummy tuck + breast lift/augmentation. Restores pre-pregnancy contour comprehensively.',
      bestFor: 'Post-pregnancy comprehensive restoration',
      duration: '5-6 hrs',
      anesthesia: 'General',
      stay: '2 days',
      price: '₹2,50,000 — ₹3,00,000',
    },
    {
      title: 'Reverse Tummy Tuck',
      description: 'Specialised technique for upper abdominal looseness via inframammary scar.',
      bestFor: 'Upper abdomen excess (rare)',
      duration: '2-3 hrs',
      anesthesia: 'General',
      stay: '1 day',
      price: '₹1,60,000 — ₹2,00,000',
    },
  ],
  walkthrough: [
    { step: 'Step 1', title: 'Pre-op Preparation (60 min)', detail: 'Pre-op photographs, markings while standing, blood thinner check, compression stockings applied for clot prevention.' },
    { step: 'Step 2', title: 'Anaesthesia (15 min)', detail: 'General anaesthesia administered by board-certified anaesthetist. Continuous monitoring throughout.' },
    { step: 'Step 3', title: 'Incision & Skin Lift (60 min)', detail: 'Low transverse incision in bikini line. Skin and fat lifted off abdominal wall up to ribcage.' },
    { step: 'Step 4', title: 'Muscle Repair (45-60 min)', detail: 'Separated rectus muscles brought back to midline with permanent sutures, creating an "internal corset". Restores core strength.' },
    { step: 'Step 5', title: 'Navel Repositioning (15 min)', detail: 'Navel is freed from old position and brought through new opening at correct height. Critical for natural appearance.' },
    { step: 'Step 6', title: 'Liposuction (if combined) (45-60 min)', detail: 'Flanks, hips, and back contoured with liposuction for circumferential result.' },
    { step: 'Step 7', title: 'Skin Closure (45-60 min)', detail: 'Excess skin trimmed precisely. Drains placed for 5-7 days. Skin closed in layers with absorbable sutures. Compression garment applied.' },
  ],
  recovery: [
    { when: 'Day 0-1', title: 'Hospital stay', detail: '1-2 nights in hospital. Walking with assistance. Drains in place. Pain medication. Compression garment full-time.' },
    { when: 'Day 2-7', title: 'At home recovery', detail: 'Walking 5-10 minutes hourly to prevent clots. Drains removed at Day 5-7. Sleep slightly bent at hips.' },
    { when: 'Week 2', title: 'Return to office work', detail: 'Sedentary work resumed at 2 weeks. Driving cleared. Compression garment 24/7.' },
    { when: 'Week 4-6', title: 'Garment downgrade', detail: 'Switch to lighter compression. Light cardio okay. Abdomen still tight when standing fully upright.' },
    { when: 'Month 3', title: 'Most activities resumed', detail: 'Heavier exercise cleared. 80% of swelling resolved. Final shape becoming evident.' },
    { when: 'Month 6', title: 'Full recovery', detail: 'Final aesthetic shape visible. Core strength returns to normal. Scar maturation begins.' },
    { when: 'Month 12', title: 'Final result', detail: 'Scar fades to barely visible pink line. Permanent muscle repair holds. Long-term flat contour.' },
  ],
  beforeAfterImage: '/images/body/before-after.webp',
  faqs: [
    {
      q: 'How much does a tummy tuck cost in Hyderabad?',
      a: 'Tummy tuck cost ranges from ₹1,40,000 to ₹2,80,000. Mini: ₹1.4L-₹1.8L. Full: ₹1.8L-₹2.2L. Extended: ₹2.2L-₹2.8L. With 360° lipo: ₹2.2L-₹2.8L. Mommy makeover: ₹2.5L-₹3L. EMI options available.',
    },
    {
      q: 'Can I have a baby after tummy tuck?',
      a: 'Yes, you can have a baby after a tummy tuck — but it is strongly recommended to complete your family BEFORE tummy tuck. Pregnancy after abdominoplasty stretches the repaired muscles and skin, often requiring revision surgery. If you do conceive, the muscle repair holds in many cases, but results may be partially lost.',
    },
    {
      q: 'How long is the recovery after a tummy tuck?',
      a: 'Hospital stay 1-2 days. Desk work in 2 weeks. Light cardio 4-6 weeks. Full activity 8-12 weeks. Final result visible at 6 months. Scar matures over 12 months.',
    },
    {
      q: 'Will the tummy tuck scar be visible?',
      a: 'The scar is positioned low across the bikini line — designed to be hidden by underwear and swimwear. It runs hip-to-hip for a full tuck. Initially pink, the scar fades to a thin pale line over 12 months. Scar massage and silicone gel can optimise appearance.',
    },
    {
      q: 'How painful is tummy tuck recovery?',
      a: 'Tummy tuck has the most uncomfortable recovery of common cosmetic procedures because the abdominal muscles are repaired. Pain is significant for the first week, moderate for 2-3 weeks. Pain medication and proper positioning (slightly bent at hips) reduce discomfort.',
    },
    {
      q: 'What is the difference between tummy tuck and liposuction?',
      a: 'Liposuction removes fat through small incisions but cannot remove loose skin or repair separated muscles. Tummy tuck addresses skin excess, muscle separation, AND fat (when combined with lipo). After pregnancy or significant weight loss, you almost always need a tummy tuck — lipo alone leaves loose skin.',
    },
    {
      q: 'Will tummy tuck remove stretch marks?',
      a: 'Stretch marks below the navel are physically excised with the skin removed during a tummy tuck — they are gone permanently. Stretch marks above the navel cannot be removed (only the skin below the navel is removed) but they may be lightened slightly as the upper skin is stretched downward.',
    },
    {
      q: 'When can I sleep flat after tummy tuck?',
      a: 'You will sleep with hips bent (recliner or pillows under knees) for 2-3 weeks to reduce tension on the abdominal closure. Most patients return to sleeping flat at 3-4 weeks once tightness has settled.',
    },
    {
      q: 'Can men have a tummy tuck?',
      a: 'Yes — male tummy tuck is increasingly common, especially after major weight loss. The technique focuses on flat, masculine contour without feminine waist curvature. Often combined with liposuction of flanks and chest contouring (gynecomastia).',
    },
    {
      q: 'What complications should I be aware of?',
      a: 'Risks include seroma (fluid collection), hematoma, infection, scar issues, deep vein thrombosis (managed with stockings and walking), wound healing problems (especially in smokers), and rarely necrosis of skin edges. Smoking dramatically increases complications and is contraindicated for 6 weeks before/after.',
    },
    {
      q: 'How long should I wait after pregnancy for a tummy tuck?',
      a: 'Wait at least 6-12 months after delivery, and complete breastfeeding. Achieve a stable weight (within 5-7 kg of your goal). Hormones, fluid retention, and skin changes need time to stabilise for predictable results.',
    },
    {
      q: 'How do I book a tummy tuck consultation?',
      a: 'Call or WhatsApp 9949808628. The clinic is at Idea Clinic, Kondapur, Hyderabad — Mon-Sat, 10AM-12PM and 7PM-8PM. All consultations are confidential.',
    },
  ],
  formGradeOptions: [
    'Mini tummy tuck',
    'Full tummy tuck',
    'Extended tummy tuck',
    'Tummy tuck + 360° liposuction',
    'Mommy makeover (with breasts)',
    'Not sure — need consultation',
  ],
  formSubject: 'New Tummy Tuck Consultation Request',
  whatsappMessage: 'Hello Dr. Ram Prabhu, I would like to book a tummy tuck consultation. Please share available slots and pricing.',
  relatedPages: [
    { url: '/liposuction-hyderabad', label: 'Liposuction' },
    { url: '/breast-augmentation-hyderabad', label: 'Breast Augmentation' },
    { url: '/services/body-contouring', label: 'Body Contouring' },
  ],
};

const TummyTuckHyderabad: React.FC = () => <MoneyPageTemplate data={data} />;
export default TummyTuckHyderabad;
